---
format: html
---

::: {style="text-align: center;"}
# Curriculum Vitae

[Download Full CV (PDF)](CV.pdf){target="_blank"}

## Charles C. Peterson, Ph.D.

**High-Performance Computing R&D Scientist**  
**Email**: [Charles.C.Peterson3@gmail.com](mailto:Charles.C.Peterson3@gmail.com)  
**Website**: [CharlesPeterson.dev](https://CharlesPeterson.dev)  
:::

Interdisciplinary researcher, collaborator, and information technology professional with over ten years of experience in scientific computing and computational research applications across STEM and non-STEM areas. My focus is in applying advanced High-Performance Computing (HPC) capabilities to enhance research throughput that involves closely collaborating with a diverse research community. My interests are using data modeling (Artificial Intelligence and Big Data techniques) and molecular modeling to describe Rare Earth Element systems. Using HPC and other advanced scientific computing techniques is essential to expand research by developing computational protocols to study heavy element chemistry with national security and other applications.

## Skills {#skills}

::: {.grid}
::: {.g-col-4}
### Programming
- Python, R, C/C++, Fortran

### Tools
- RStudio, Jupyter, Containerized Software

### Scientific Expertise
- Computational Chemistry
- Physical Chemistry
- Nuclear Chemistry
- Spectroscopy
:::
::: {.g-col-4}
### Data Analysis
- Machine Learning
- Artificial Intelligence
- Bioinformatics
- Numerical Analysis
- Data Visualization

### Professional Skills
- HPC System Administration
- Linux Administration
- Parallel Filesystems
- Fast Computer Network Communications
- Scalable Parallel Programming
- GPU Programming
- Big Data Analysis
- Molecular Modeling
- Relativistic Chemistry
- Material Science
:::
::: {.g-col-4}
### Collaborative and Communication Skills
- Scientific Consultation
- Multidisciplinary Collaboration
- Scientific Writing
:::
:::

## Work Experience {#work-experience}

::: {.callout-important collapse="true"}
### Senior HPC System Administrator
- **Organization**: Office of Advanced Research Computing, University of California, Los Angeles
- **Years**: December 2020 – Present
- **Responsibilities**:
  - Operate UCLA’s HPC resources and provide consultation services.
  - Install and maintain hardware and software for scientific applications.
  - Ensure applications run at maximum efficiency.
:::

::: {.callout-important collapse="true"}
### Research Scientist II
- **Organization**: North Texas Scientific Computing, University of North Texas
- **Years**: November 2019 – December 2020
- **Responsibilities**:
  - Provide consultation services for UNT researchers.
  - Explore grant opportunities and evaluate HPC technologies.
  - Mentor and instruct graduate students.
  - Perform research in AI and machine learning applications.
:::

::: {.callout-important collapse="true"}
### Cross-Functional IT Support Analyst
- **Organization**: Research IT Services, University of North Texas
- **Years**: February 2018 – November 2019
- **Responsibilities**:
  - Enhance scientific computing resources.
  - Optimize software and libraries for materials science and data analytics.
  - Conduct community training and outreach programs.
:::

::: {.callout-important collapse="true"}
### IT Manager I – High Performance Computing
- **Organization**: Academic Computing & User Services, University of North Texas
- **Years**: April 2015 – February 2018
- **Responsibilities**:
  - Maintain HPC resources and allocations.
  - Provide end-user HPC support and software development.
:::

::: {.callout-important collapse="true"}
### Graduate Research Assistant
- **Organization**: Center for Advanced Scientific Computing and Modeling (CASCaM), University of North Texas
- **Years**: May 2008 – December 2015
- **Responsibilities**:
  - Develop composite strategies for computational quantum chemistry.
  - Advance theoretical techniques for simulating chemical properties.
  - Conduct studies on energetics of silicon modules, noble gases, and small lanthanide systems.
:::

## Education {#education}

::: {.callout-tip collapse="true"}
### Doctor of Philosophy in Physical Chemistry
- **Institution**: University of North Texas, Denton, TX
- **Year**: December 2015
- **Dissertation**: Accurate Energetics across the Periodic Table via Quantum Chemistry
:::

::: {.callout-tip collapse="true"}
### Bachelor of Science in Chemistry
- **Institution**: University of North Texas, Denton, TX
- **Year**: May 2009
- **Major**: Chemistry
- **Minor**: Computer Science
:::

## Professional Activities {#professional-activities}

::: {.callout-note collapse="true"}
### Publication and Editorial Service
- Reviewer  
  - Journal of Chemical Information and Modeling
  - Journal of Radioanalytical and Nuclear Chemistry
  - Royal Society of Chemistry Advances
  - PEARC21 conference
  - XSEDE EMPOWER Program
- Editor, American Chemical Society Book Series “Computational Science Applications in Nuclear and Radiochemistry”, 2020
- HPC allocation management for University of North Texas HPC allocations, 2015 - 2022 
:::

::: {.callout-note collapse="true"}
### Professional Organizations

- **Senior Scientific Fellow**, Institute for Nuclear Security, Howard H. Baker Jr. Center for Public Policy, University of Tennessee, Knoxville, TN (06/2017 – 2024)
  - Focus: High-Performance Computing applications in national and nuclear security.
- **Member of ÚNeTe** – Latinx Faculty/Staff Alliance at University of North Texas, 2020 
- **Member of American Chemical Society**
  - Division of Nuclear Chemistry & Technology (2015 - Present)
  - Division of History (2015 - 2016)
  - Division of Physical Chemistry (2015 - 2016)
- **Member of Association for Computing Machinery SIGHPC** (2020 – 2024)
- **XSEDE Campus Champion** UNT (06/2016 – 12/2020)
  - Provides access and application support to researchers and students in NSF eXtreme Scale Engineering Discovery Environment (XSEDE) computational resources.
:::

::: {.callout-note collapse="true"}
### Committee and Organizational Activities
- **Member**
  - AI Accelerator Program, UCLA OARC, 2024
  - AI for Environmental Remediation, 2023-Present
  - Diversity, Equity, and Inclusion Action Committee (DEIAC), Nuclear Engineering, University of Tennessee (2020 - 2024)
- **Social Media Manager** for UNT Research IT Services (2018 - 2020)
- **Chair**
  - American Chemical Society Annual Meeting, Nuclear Chemistry and Technology Division (ACS NUCL), Session “Data Science & Artificial Intelligence Applications in Nuclear and Radiochemistry” (05/2021, 05/2022, 08/2022, and 08/2023)
  - American Chemical Society Annual Meeting, Nuclear Chemistry and Technology Division (ACS NUCL), Session “Computational Methods for Lanthanides & Actinides: Theory & Applications” (08/2020, 05/2020, 08/2019, 05/2019, and 08/2018)
- **Presider**
  - American Chemical Society Annual Meeting, Nuclear Chemistry and Technology Division (ACS NUCL), Session “Computational Methods for Lanthanides & Actinides: Theory & Applications” (05/2020, 08/2019, 08/2018, and 05/2018)
  - American Chemical Society Annual Meeting, Division of Physical Chemistry (ACS PHYS), Session “Thermodynamics, reactivity, and spectroscopy of the heavy elements” (05/2014)
:::

::: {.callout-note collapse="true"}
### Professional Training {#professional-training}
- **DataCamp Certification**
  - AI Fundamentals, 2024
  - Data Literacy, 2024
- **AI Core Capabilities**, UCLA OARC, Training in AI's furture potential, risks, and direction to deliver effective research-foused AI services to support research at UCLA, 2024
- **QMCPack User Workshop**, Oak Ridge National Laboratory, TN (05/2019)
  - Workshop for current users and developers. Training in added features and planned improvements for the electronic structure code, QMCPACK.
- **OpenFabrics Alliance Workshop**, Austin, TX (03/2017)
  - Focused on the emerging needs of high-performance networks and discussed challenges in computing over high-speed networks.
- **DDN EXAScaler Technical Training**, Colorado Spring, CO (02/2016)
  - Training on high-performance parallel file systems, large data storage, and Lustre design for Big Data projects.
- **XSEDE/PRACE EU-US HPC Summer School**, Dublin, Ireland (06/2012)
  - Summer school addressing challenges of High-Performance Computing in computational sciences, including interactive training on programming skills and software libraries.
:::

## Awards and Recognitions {#awards-and-recognitions}

::: {.callout-note collapse="true"}
### Awards and Recognitions
- “Extra Mile” Award – University of North Texas (2018)
- Tuition Reduction Benefit Award - University of North Texas (2015)
- Graduate Research Assistant Scholarship - University of North Texas (2009)
- Dallas/Fort Worth American Chemical Society Award (2009)
- J. L. Carrico Award - Department of Chemistry, University of North Texas (2009)
- American Chemical Society Analytical Chemistry Award (2008)
- Undergraduate Dean’s List - University of North Texas (2005, 2006, 2008)
:::

## Publications {#publications}

::: {.callout-note collapse="true"}
### Selected Presentations
- Charles C. Peterson, “Singularity on Hoffman2: Using containers on HPC resources” Workshop Series, UCLA, 04/29/2021.
- Charles C. Peterson, D. A. Penchoff, “Understanding Binding Selectivity of Lanthanide and Actinide Compounds by Computational Protocols” International Workshop, 2020.
- Charles C. Peterson, “Machine Learning Techniques with High Performance Computing” Invited Webinar, University of Tennessee, 2019.
:::

::: {.callout-note collapse="true"}
### Complete List of Publications

- Edward F. Valeev, Robert J. Harrison, Charles C. Peterson, Deborah A. Penchoff, “Direct determination of optimal real-space orbitals for correlated electronic structure of molecules”, J. Chem. Theory Comput, 2023.
- Deborah A. Penchoff, Charles C. Peterson, Eleigha M. Wrancher, George Bosilca, Robert J. Harrison, Edward F. Valeev, Paul D. Benny, “Evaluations of Molecular Modeling and Machine Learning for Predictive Capabilities in Binding of Lanthanum and Actinium with Carboxylic Acids”, JRNC, 331 (12), 2022.
- Edward F. Valeev, Robert J. Harrison, Charles C. Peterson, Deborah A. Penchoff, “Direct determination of optimal real-space orbitals for correlated electronic structure of molecules”, arXiv:2207.10841, 2022.
- Joseph F. DeJesusa, Ryan W. F. Kerr, Deborah A. Penchoff, Xian B. Carrolla, Charles C. Peterson, Polly L. Arnold and David M. Jenkins. “Actinide tetra-N-heterocyclic carbene sandwiches”. Chem. Sci., 2021.
- Deborah A. Penchoff, Charles C. Peterson, Eleigha M. Wrancher, George K. Schweitzer, Robert J. Harrison, Rose A. Boll, Paul D. Benny, Howard L. Hall. “Evaluating Complexation of Lanthanum and Actinium for Applications in Radiochemical Separations”. American Chemical Society Book series “Computational Science for Lanthanides and Actinides”, 2020. Invited chapter.
- Charles C. Peterson, Jack Burn, Deborah A. Penchoff. “Artificial Intelligence in Nuclear and Radiochemistry” – American Chemical Society Book Series “Computational Science for Lanthanides and Actinides”, 2021. Invited chapter. 
- Charles C. Peterson, Deborah A. Penchoff, John D. Auxier II, Howard L. Hall, “Establishing Cost-Effective Computational Models for the Prediction of Lanthanoid Binding in [Ln(NO3)]2+ (with Ln = La to Lu)”, ACS Omega, 2019, 4, 1, 1375-1385.
- Deborah A. Penchoff, Charles C. Peterson, Jon P. Camden, James Bradshaw, John D. Auxier II, George K. Schweitzer, David M. Jenkins, Robert J. Harrison, Howard L. Hall, “Structural Analysis of the Complexation of Uranyl, Neptunyl, Plutonyl, and Americyl with Cyclic Imide Dioximes”, ACS Omega, 2018, 3, 10, 13984-13993.
- Deborah A. Penchoff, Charles C. Peterson, Mark S. Quint, John D. Auxier II, George K. Schweitzer, David M. Jenkins, Robert J. Harrison, Howard L. Hall. “Structural Characteristics, Populations Analysis, and Binding Energies of [An(NO3)]2+, [with An = Ac – Lr]”, ACS Omega, 2018, 3, 10, 14127-14143.
- Charles Peterson, Deborah A. Penchoff, and Angela K. Wilson, “Prediction of thermochemical properties across the periodic table: A review of correlation consistent Composite Approach (ccCA) strategies and applications” Annual Reports in Computational Chemistry, Vol. 12, 2016. 
- Charles Peterson, Deborah A. Penchoff, and Angela K. Wilson, “Ab initio approaches for the determination of heavy element energetics: Ionization energies of trivalent lanthanides (Ln = La-Eu)” J. Chem. Phys., 2015, 143, 19, 194109.
- Cong Liu, Charles Peterson, and Angela K. Wilson, “C-O Bond Cleavage of Dimethyl Ether by Transition Metal Ions: A Systematic Study on Catalytic Properties of Metals and Performance of DFT Functionals” J. Phys. Chem. A, 2013, 117, 5140.
- Gbenga A. Oyedepo, Charles Peterson, George Schoendorff, and Angela K. Wilson, “Spectroscopic properties of Arx-Zn and Arx-Ag+ (x=1,2) van der Waals complexes” J. Chem. Phys., 2013, 138, 104116.
- Gbenga A. Oyedepo, Charles Peterson, and Angela K. Wilson, “Accurate predictions of the energetics of silicon compounds using the multireference correlation consistent composite approach” J. Chem. Phys., 2011, 135, 094103.[Insert comprehensive list of publications here.]
:::

## Presentations {#presentations}

::: {.callout-note collapse="true"}
### Workshops
- Charles C. Peterson “Big Data on HPC”, Workshop Series, UCLA, 06/29/2023
- Charles C. Peterson, “Hoffman2 Happy Hour: Using RStudio”, Workshop Series, UCLA, 09/28/2022.
- Charles C. Peterson, “Hoffman2 Happy Hour: Anaconda”, Workshop Series, UCLA, 09/21/2022.
- Charles C. Peterson, “Building Containers for HPC”, Workshop Series, UCLA, 07/06/2022.
- Charles C. Peterson, “Using Containers on HPC Resources”, Workshop Series, UCLA, 04/20/2022.
- Charles C. Peterson, “Singularity on Hoffman2: Using containers on HPC resources” Workshop Series, UCLA, 04/29/2021.
:::
::: {.callout-note collapse="true"}
### Panels
- High-Performance Computing in Nuclear Technology, American Nuclear Society Student Conference Student Conference, 05/15/2023
:::

::: {.callout-note collapse="true"}
### Selected Presentations
- Charles C. Peterson, Deborah A. Penchoff “REACKT: Advancing Separations of Lanthanides and Actinides” ACS National Meeting and Expo, Division of Nuclear Chemistry and Technology, Session: Nuclear Forensics, Fall 2024.
- Charles C. Peterson, Deborah A. Penchoff “Advanced Computational Strategies for Lanthanide and Actinide Systems” ACS National Meeting and Expo, Division of Nuclear Chemistry and Technology, Fall 2023.
:::

::: {.callout-note collapse="true"}
### Complete List of Presentations
- Charles C. Peterson, Deborah A. Penchoff “REACKT: Advancing Separations of Lanthanides and Actinides” ACS National Meeting and Expo, Division of Nuclear Chemistry and Technology, Fall 2024.
- Charles C. Peterson, Deborah A. Penchoff “Advanced Computational Strategies for Lanthanide and Actinide Systems” ACS National Meeting and Expo, Division of Nuclear Chemistry and Technology, Fall 2023.
- Charles C. Peterson, D. A. Penchoff, “Understanding Binding Selectivity of Lanthanide and Actinide Compounds by Computational Protocols” International Workshop on Theory Frontiers in Actinide Sciences: Chemistry and Materials, Santa Fe, NM, 02/2 – 5/2020.
- Charles C. Peterson, D. A. Penchoff, “Understanding Binding Selectivity of Lanthanides and Actinides by Computational Protocols” 64th Annual Radiobioassy & Radiochemical Measurements Conference, Santa Fe, NM, 08/28 – 30/2019.
- Charles C. Peterson “Machine Learning Techniques with High Performance Computing” Invited Webinar, Institute for Nuclear Security, University of Tennessee, Knoxville TN, 08/05/2019.
- Charles C. Peterson, D. A. Penchoff, “Computational protocol for binding selectivity of lanthanide and actinide systems” Division of Nuclear Chemistry and Technology, Computational Methods for Lanthanide & Actinide Chemistry, 258th American Chemical Society National Meeting & Exposition, San Diego CA, 08/ 2019.
- Charles C. Peterson, D. A. Penchoff, H. L. Hall, R. J. Harrison, “Understanding selectivity of lanthanide and actinide compounds by computational techniques” Division of Nuclear Chemistry and Technology, Computational Methods for Lanthanide & Actinide Chemistry, 257th American Chemical Society National Meeting & Exposition, Orlando FL, 05/2019.
- Charles C. Peterson, D. A. Penchoff, H. L. Hall, R. J. Harrison, “Utilizing computational protocols for binding selectivity of lanthanide and actinide compounds”, Division of Nuclear Chemistry and Technology, Computational Methods for Lanthanides & Actinides: Theory & Application, 256th American Chemical Society National Meeting & Exposition, Boston MA, 08/2018.
- Charles C. Peterson, “Understanding structural and thermochemical properties of actinide-containing compounds”, Division of Nuclear Chemistry and Technology, Computational Methods for Lanthanides & Actinides: Theory & Application Session, 255th American Chemical Society National Meeting & Exposition, New Orleans LA, 05/2018.
- Charles Peterson, Deborah A. Penchoff, Robert J. Harrison, “Investigation of the Selectivity of Cyclic Amidoxime Ligands to Uranyl by Theoretical Techniques”, 62nd Conference on Radiobioassay & Radiochemical Measurements, Honolulu, Hawai’i, 02/2017.
- Charles Peterson, Deborah Penchoff, Angela Wilson” Composite Approaches for accurate predictions of lanthanide and actinide chemistry” Division of Computers in Chemistry, Quantum Mechanics Session, 252nd American Chemical Society National Meeting & Exposition, Philadelphia PA, 08/2016.
- Charles Peterson, Deborah Penchoff, Angela Wilson, “Composite Approach Towards Accurate Predictions of Lanthanide and Actinide Thermochemistry” Division of Computers in Chemistry, Quantum Mechanics Session, 251st American Chemical Society National Meeting & Exposition, San Diego CA, 05/2016.
- Charles Peterson, Angela Wilson, “Ab initio Approaches for Accurate Predictions of Lanthanide Thermochemistry”, Division of Physical Chemistry, Physical Chemistry Poster Session 249th American Chemical Society National Meeting & Exposition, Denver CO, 05/2015.
- Charles Peterson, Angela K. Wilson, “Ab initio Approaches for the Predictions of Energetic Properties of Lanthanides”, Division of Physical Chemistry, Thermodynamics, Reactivity, and Spectroscopy of the Heavy Elements Fundamental Advances in Theory and Computation Session, 247th American Chemical Society National Meeting & Exposition, Dallas TX, 05/2014.
- Charles Peterson, Angela K. Wilson, “C-O Bond Activation of Dimethyl Ether by Transition Metal Ions”, 24th Austin Symposium on Molecular Structure and Dynamics at Dallas, 05/2014.
- Charles Peterson, Angela K. Wilson “Designing Advance Ab Initio Composite Methods for Scalable Computing” XSEDE/PRACE EU-US High Performance Computing Summer School, 06/2012, Dublin, Ireland.
- Charles Peterson, Angela K. Wilson, “Accurate Predictions of Energetic Properties using the Multi-Reference correlation consistent Composite Approach (MR-ccCA)”, 22nd Austin Symposium on Molecular Structure and Dynamics, 05/2012.
- Charles Peterson, Angela K. Wilson, “MR-ccCA Predictions of the Energetics of Silicon-containing Compounds", Physical Division, 44th American Chemical Society Meeting in Miniature, Tarleton State University, 04/2011.
- Charles Peterson, Angela K. Wilson, “MR-ccCA Predictions of the Energetics of Silicon-containing Compounds”, Poster Session, Southwest Theoretical Chemistry Conference, University of North Texas, 10/2010.
- Charles Peterson, Angela K. Wilson, “Application of the Multi-Reference correlation consistent Composite Approach (MR-ccCA)”, Physical Division, 43rd American Chemical Society Meeting in Miniature, University of Texas at Dallas, 04/2010.
:::

[Back to Top](#curriculum-vitae)
