---
title: "Paper on Numberically Exact Orbitals"
author: "Charles Peterson"
date: "2022-07-22"
categories: [chemistry, publication]

---

[New paper](https://arxiv.org/abs/2207.10841) submitted by my co-workers (Edward F. Valeev, Robert J. Harrison, Deborah A. Penchoff) and myself.

Direct determination of optimal real-space orbitals for correlated electronic structure of molecules

Abstract:

We demonstrate how to determine nearly numerically exact orthonormal orbitals that are optimal for evaluation of the energy of arbitrary (correlated) states of atoms and molecules by minimization of the energy Lagrangian. Orbitals are expressed in real space using multiresolution spectral element basis that is refined adaptively to achieve the user-specified target precision while avoiding the ill-conditioning issues that plague AO basis set expansions traditionally used for correlated models of molecular electronic structure. For light atoms the orbital solver in conjunction with a variational electronic structure model [selected Configuration Interaction (CI)] provides energies of comparable precision to a state-of-the-art atomic CI solver. The computed electronic energies of atoms and molecules are significantly more accurate than the counterparts obtained with the Gaussian AO bases of the same rank, and can be determined even when linear dependence issues preclude the use of the AO bases.
